FROM frooodle/s-pdf:0.44.1

EXPOSE 8080

COPY ./stirling-pdf/customFiles/static/* /customFiles/static/

ENV DOCKER_ENABLE_SECURITY=false
ENV SECURITY_ENABLE_LOGIN=false
ENV INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
ENV SYSTEM_DEFAULT_LOCALE=sr-RS
ENV APP_LOCALE=sr-RS
ENV SYSTEM_CUSTOM_STATIC_FILE_PATH=/customFiles/static/
ENV LANGS="sr_LATN_RS,en_US"
ENV UI_APP_NAME="PDF alati"
ENV UI_HOME_DESCRIPTION="Konverzije PDF dokumenata u Word, Excel, PowerPoint, JPG, PNG, HTML i obrnuto."
ENV UI_APP_NAVBAR_NAME="PDF alati"
ENV SYSTEM_MAX_FILE_SIZE="100"
ENV METRICS_ENABLED="true"
ENV SYSTEM_GOOGLEVISIBILITY="true"
ENV API_ENABLED="true"
ENV API_REQUIRE_LOGIN="false"
ENV API_SHOW_DOCS="true"
ENV SECURITY_CSRF_DISABLED="true"
ENV SECURITY_CSRF_COOKIE_SECURE="false"
ENV SECURITY_ENABLE_CORS="true"
ENV SECURITY_CORS_ALLOWED_ORIGINS="*"
ENV SECURITY_ACTUATOR_PUBLIC="true"
ENV ENDPOINTS_HEALTH_SENSITIVE="false"
ENV MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE="*"
ENV SECURITY_CUSTOM_GLOBAL_API_KEY="pdf-api-key"
