services:
  stirling-pdf:
    image: frooodle/s-pdf:0.28.1
    ports:
      - "8080:8080"
    volumes:
      - ./stirling-pdf/customFiles/static:/customFiles/static
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -qv 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
      SYSTEM_DEFAULTLOCALE: sr_LATN_RS
      SYSTEM_CUSTOM_STATIC_FILE_PATH: /customFiles/static/
      LANGS: "sr_LATN_RS,en_US"
      UI_APPNAME: PDF alati
      UI_HOMEDESCRIPTION: Konverzije PDF dokumenata u Word, Excel, PowerPoint, JPG, PNG, HTML i obrnuto.
      UI_APPNAMENAVBAR: PDF alati
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "false"
      SYSTEM_GOOGLEVISIBILITY: "true"
    restart: on-failure:5
